use crate::common::Location;

pub const LINES: [[Location; 4]; 76] = [
    [
        Location { x: 0, y: 0, z: 0 },
        Location { x: 0, y: 0, z: 1 },
        Location { x: 0, y: 0, z: 2 },
        Location { x: 0, y: 0, z: 3 },
    ],
    [
        Location { x: 0, y: 1, z: 0 },
        Location { x: 0, y: 1, z: 1 },
        Location { x: 0, y: 1, z: 2 },
        Location { x: 0, y: 1, z: 3 },
    ],
    [
        Location { x: 0, y: 2, z: 0 },
        Location { x: 0, y: 2, z: 1 },
        Location { x: 0, y: 2, z: 2 },
        Location { x: 0, y: 2, z: 3 },
    ],
    [
        Location { x: 0, y: 3, z: 0 },
        Location { x: 0, y: 3, z: 1 },
        Location { x: 0, y: 3, z: 2 },
        Location { x: 0, y: 3, z: 3 },
    ],
    [
        Location { x: 0, y: 0, z: 0 },
        Location { x: 0, y: 1, z: 0 },
        Location { x: 0, y: 2, z: 0 },
        Location { x: 0, y: 3, z: 0 },
    ],
    [
        Location { x: 0, y: 0, z: 1 },
        Location { x: 0, y: 1, z: 1 },
        Location { x: 0, y: 2, z: 1 },
        Location { x: 0, y: 3, z: 1 },
    ],
    [
        Location { x: 0, y: 0, z: 2 },
        Location { x: 0, y: 1, z: 2 },
        Location { x: 0, y: 2, z: 2 },
        Location { x: 0, y: 3, z: 2 },
    ],
    [
        Location { x: 0, y: 0, z: 3 },
        Location { x: 0, y: 1, z: 3 },
        Location { x: 0, y: 2, z: 3 },
        Location { x: 0, y: 3, z: 3 },
    ],
    [
        Location { x: 0, y: 0, z: 0 },
        Location { x: 0, y: 1, z: 1 },
        Location { x: 0, y: 2, z: 2 },
        Location { x: 0, y: 3, z: 3 },
    ],
    [
        Location { x: 0, y: 0, z: 3 },
        Location { x: 0, y: 1, z: 2 },
        Location { x: 0, y: 2, z: 1 },
        Location { x: 0, y: 3, z: 0 },
    ],
    [
        Location { x: 1, y: 0, z: 0 },
        Location { x: 1, y: 0, z: 1 },
        Location { x: 1, y: 0, z: 2 },
        Location { x: 1, y: 0, z: 3 },
    ],
    [
        Location { x: 1, y: 1, z: 0 },
        Location { x: 1, y: 1, z: 1 },
        Location { x: 1, y: 1, z: 2 },
        Location { x: 1, y: 1, z: 3 },
    ],
    [
        Location { x: 1, y: 2, z: 0 },
        Location { x: 1, y: 2, z: 1 },
        Location { x: 1, y: 2, z: 2 },
        Location { x: 1, y: 2, z: 3 },
    ],
    [
        Location { x: 1, y: 3, z: 0 },
        Location { x: 1, y: 3, z: 1 },
        Location { x: 1, y: 3, z: 2 },
        Location { x: 1, y: 3, z: 3 },
    ],
    [
        Location { x: 1, y: 0, z: 0 },
        Location { x: 1, y: 1, z: 0 },
        Location { x: 1, y: 2, z: 0 },
        Location { x: 1, y: 3, z: 0 },
    ],
    [
        Location { x: 1, y: 0, z: 1 },
        Location { x: 1, y: 1, z: 1 },
        Location { x: 1, y: 2, z: 1 },
        Location { x: 1, y: 3, z: 1 },
    ],
    [
        Location { x: 1, y: 0, z: 2 },
        Location { x: 1, y: 1, z: 2 },
        Location { x: 1, y: 2, z: 2 },
        Location { x: 1, y: 3, z: 2 },
    ],
    [
        Location { x: 1, y: 0, z: 3 },
        Location { x: 1, y: 1, z: 3 },
        Location { x: 1, y: 2, z: 3 },
        Location { x: 1, y: 3, z: 3 },
    ],
    [
        Location { x: 1, y: 0, z: 0 },
        Location { x: 1, y: 1, z: 1 },
        Location { x: 1, y: 2, z: 2 },
        Location { x: 1, y: 3, z: 3 },
    ],
    [
        Location { x: 1, y: 0, z: 3 },
        Location { x: 1, y: 1, z: 2 },
        Location { x: 1, y: 2, z: 1 },
        Location { x: 1, y: 3, z: 0 },
    ],
    [
        Location { x: 2, y: 0, z: 0 },
        Location { x: 2, y: 0, z: 1 },
        Location { x: 2, y: 0, z: 2 },
        Location { x: 2, y: 0, z: 3 },
    ],
    [
        Location { x: 2, y: 1, z: 0 },
        Location { x: 2, y: 1, z: 1 },
        Location { x: 2, y: 1, z: 2 },
        Location { x: 2, y: 1, z: 3 },
    ],
    [
        Location { x: 2, y: 2, z: 0 },
        Location { x: 2, y: 2, z: 1 },
        Location { x: 2, y: 2, z: 2 },
        Location { x: 2, y: 2, z: 3 },
    ],
    [
        Location { x: 2, y: 3, z: 0 },
        Location { x: 2, y: 3, z: 1 },
        Location { x: 2, y: 3, z: 2 },
        Location { x: 2, y: 3, z: 3 },
    ],
    [
        Location { x: 2, y: 0, z: 0 },
        Location { x: 2, y: 1, z: 0 },
        Location { x: 2, y: 2, z: 0 },
        Location { x: 2, y: 3, z: 0 },
    ],
    [
        Location { x: 2, y: 0, z: 1 },
        Location { x: 2, y: 1, z: 1 },
        Location { x: 2, y: 2, z: 1 },
        Location { x: 2, y: 3, z: 1 },
    ],
    [
        Location { x: 2, y: 0, z: 2 },
        Location { x: 2, y: 1, z: 2 },
        Location { x: 2, y: 2, z: 2 },
        Location { x: 2, y: 3, z: 2 },
    ],
    [
        Location { x: 2, y: 0, z: 3 },
        Location { x: 2, y: 1, z: 3 },
        Location { x: 2, y: 2, z: 3 },
        Location { x: 2, y: 3, z: 3 },
    ],
    [
        Location { x: 2, y: 0, z: 0 },
        Location { x: 2, y: 1, z: 1 },
        Location { x: 2, y: 2, z: 2 },
        Location { x: 2, y: 3, z: 3 },
    ],
    [
        Location { x: 2, y: 0, z: 3 },
        Location { x: 2, y: 1, z: 2 },
        Location { x: 2, y: 2, z: 1 },
        Location { x: 2, y: 3, z: 0 },
    ],
    [
        Location { x: 3, y: 0, z: 0 },
        Location { x: 3, y: 0, z: 1 },
        Location { x: 3, y: 0, z: 2 },
        Location { x: 3, y: 0, z: 3 },
    ],
    [
        Location { x: 3, y: 1, z: 0 },
        Location { x: 3, y: 1, z: 1 },
        Location { x: 3, y: 1, z: 2 },
        Location { x: 3, y: 1, z: 3 },
    ],
    [
        Location { x: 3, y: 2, z: 0 },
        Location { x: 3, y: 2, z: 1 },
        Location { x: 3, y: 2, z: 2 },
        Location { x: 3, y: 2, z: 3 },
    ],
    [
        Location { x: 3, y: 3, z: 0 },
        Location { x: 3, y: 3, z: 1 },
        Location { x: 3, y: 3, z: 2 },
        Location { x: 3, y: 3, z: 3 },
    ],
    [
        Location { x: 3, y: 0, z: 0 },
        Location { x: 3, y: 1, z: 0 },
        Location { x: 3, y: 2, z: 0 },
        Location { x: 3, y: 3, z: 0 },
    ],
    [
        Location { x: 3, y: 0, z: 1 },
        Location { x: 3, y: 1, z: 1 },
        Location { x: 3, y: 2, z: 1 },
        Location { x: 3, y: 3, z: 1 },
    ],
    [
        Location { x: 3, y: 0, z: 2 },
        Location { x: 3, y: 1, z: 2 },
        Location { x: 3, y: 2, z: 2 },
        Location { x: 3, y: 3, z: 2 },
    ],
    [
        Location { x: 3, y: 0, z: 3 },
        Location { x: 3, y: 1, z: 3 },
        Location { x: 3, y: 2, z: 3 },
        Location { x: 3, y: 3, z: 3 },
    ],
    [
        Location { x: 3, y: 0, z: 0 },
        Location { x: 3, y: 1, z: 1 },
        Location { x: 3, y: 2, z: 2 },
        Location { x: 3, y: 3, z: 3 },
    ],
    [
        Location { x: 3, y: 0, z: 3 },
        Location { x: 3, y: 1, z: 2 },
        Location { x: 3, y: 2, z: 1 },
        Location { x: 3, y: 3, z: 0 },
    ],
    [
        Location { x: 0, y: 0, z: 0 },
        Location { x: 1, y: 0, z: 0 },
        Location { x: 2, y: 0, z: 0 },
        Location { x: 3, y: 0, z: 0 },
    ],
    [
        Location { x: 0, y: 0, z: 1 },
        Location { x: 1, y: 0, z: 1 },
        Location { x: 2, y: 0, z: 1 },
        Location { x: 3, y: 0, z: 1 },
    ],
    [
        Location { x: 0, y: 0, z: 2 },
        Location { x: 1, y: 0, z: 2 },
        Location { x: 2, y: 0, z: 2 },
        Location { x: 3, y: 0, z: 2 },
    ],
    [
        Location { x: 0, y: 0, z: 3 },
        Location { x: 1, y: 0, z: 3 },
        Location { x: 2, y: 0, z: 3 },
        Location { x: 3, y: 0, z: 3 },
    ],
    [
        Location { x: 0, y: 0, z: 0 },
        Location { x: 1, y: 0, z: 1 },
        Location { x: 2, y: 0, z: 2 },
        Location { x: 3, y: 0, z: 3 },
    ],
    [
        Location { x: 0, y: 0, z: 3 },
        Location { x: 1, y: 0, z: 2 },
        Location { x: 2, y: 0, z: 1 },
        Location { x: 3, y: 0, z: 0 },
    ],
    [
        Location { x: 0, y: 1, z: 0 },
        Location { x: 1, y: 1, z: 0 },
        Location { x: 2, y: 1, z: 0 },
        Location { x: 3, y: 1, z: 0 },
    ],
    [
        Location { x: 0, y: 1, z: 1 },
        Location { x: 1, y: 1, z: 1 },
        Location { x: 2, y: 1, z: 1 },
        Location { x: 3, y: 1, z: 1 },
    ],
    [
        Location { x: 0, y: 1, z: 2 },
        Location { x: 1, y: 1, z: 2 },
        Location { x: 2, y: 1, z: 2 },
        Location { x: 3, y: 1, z: 2 },
    ],
    [
        Location { x: 0, y: 1, z: 3 },
        Location { x: 1, y: 1, z: 3 },
        Location { x: 2, y: 1, z: 3 },
        Location { x: 3, y: 1, z: 3 },
    ],
    [
        Location { x: 0, y: 1, z: 0 },
        Location { x: 1, y: 1, z: 1 },
        Location { x: 2, y: 1, z: 2 },
        Location { x: 3, y: 1, z: 3 },
    ],
    [
        Location { x: 0, y: 1, z: 3 },
        Location { x: 1, y: 1, z: 2 },
        Location { x: 2, y: 1, z: 1 },
        Location { x: 3, y: 1, z: 0 },
    ],
    [
        Location { x: 0, y: 2, z: 0 },
        Location { x: 1, y: 2, z: 0 },
        Location { x: 2, y: 2, z: 0 },
        Location { x: 3, y: 2, z: 0 },
    ],
    [
        Location { x: 0, y: 2, z: 1 },
        Location { x: 1, y: 2, z: 1 },
        Location { x: 2, y: 2, z: 1 },
        Location { x: 3, y: 2, z: 1 },
    ],
    [
        Location { x: 0, y: 2, z: 2 },
        Location { x: 1, y: 2, z: 2 },
        Location { x: 2, y: 2, z: 2 },
        Location { x: 3, y: 2, z: 2 },
    ],
    [
        Location { x: 0, y: 2, z: 3 },
        Location { x: 1, y: 2, z: 3 },
        Location { x: 2, y: 2, z: 3 },
        Location { x: 3, y: 2, z: 3 },
    ],
    [
        Location { x: 0, y: 2, z: 0 },
        Location { x: 1, y: 2, z: 1 },
        Location { x: 2, y: 2, z: 2 },
        Location { x: 3, y: 2, z: 3 },
    ],
    [
        Location { x: 0, y: 2, z: 3 },
        Location { x: 1, y: 2, z: 2 },
        Location { x: 2, y: 2, z: 1 },
        Location { x: 3, y: 2, z: 0 },
    ],
    [
        Location { x: 0, y: 3, z: 0 },
        Location { x: 1, y: 3, z: 0 },
        Location { x: 2, y: 3, z: 0 },
        Location { x: 3, y: 3, z: 0 },
    ],
    [
        Location { x: 0, y: 3, z: 1 },
        Location { x: 1, y: 3, z: 1 },
        Location { x: 2, y: 3, z: 1 },
        Location { x: 3, y: 3, z: 1 },
    ],
    [
        Location { x: 0, y: 3, z: 2 },
        Location { x: 1, y: 3, z: 2 },
        Location { x: 2, y: 3, z: 2 },
        Location { x: 3, y: 3, z: 2 },
    ],
    [
        Location { x: 0, y: 3, z: 3 },
        Location { x: 1, y: 3, z: 3 },
        Location { x: 2, y: 3, z: 3 },
        Location { x: 3, y: 3, z: 3 },
    ],
    [
        Location { x: 0, y: 3, z: 0 },
        Location { x: 1, y: 3, z: 1 },
        Location { x: 2, y: 3, z: 2 },
        Location { x: 3, y: 3, z: 3 },
    ],
    [
        Location { x: 0, y: 3, z: 3 },
        Location { x: 1, y: 3, z: 2 },
        Location { x: 2, y: 3, z: 1 },
        Location { x: 3, y: 3, z: 0 },
    ],
    [
        Location { x: 0, y: 0, z: 0 },
        Location { x: 1, y: 1, z: 0 },
        Location { x: 2, y: 2, z: 0 },
        Location { x: 3, y: 3, z: 0 },
    ],
    [
        Location { x: 0, y: 0, z: 1 },
        Location { x: 1, y: 1, z: 1 },
        Location { x: 2, y: 2, z: 1 },
        Location { x: 3, y: 3, z: 1 },
    ],
    [
        Location { x: 0, y: 0, z: 2 },
        Location { x: 1, y: 1, z: 2 },
        Location { x: 2, y: 2, z: 2 },
        Location { x: 3, y: 3, z: 2 },
    ],
    [
        Location { x: 0, y: 0, z: 3 },
        Location { x: 1, y: 1, z: 3 },
        Location { x: 2, y: 2, z: 3 },
        Location { x: 3, y: 3, z: 3 },
    ],
    [
        Location { x: 0, y: 0, z: 0 },
        Location { x: 1, y: 1, z: 1 },
        Location { x: 2, y: 2, z: 2 },
        Location { x: 3, y: 3, z: 3 },
    ],
    [
        Location { x: 0, y: 0, z: 3 },
        Location { x: 1, y: 1, z: 2 },
        Location { x: 2, y: 2, z: 1 },
        Location { x: 3, y: 3, z: 0 },
    ],
    [
        Location { x: 0, y: 3, z: 0 },
        Location { x: 1, y: 2, z: 0 },
        Location { x: 2, y: 1, z: 0 },
        Location { x: 3, y: 0, z: 0 },
    ],
    [
        Location { x: 0, y: 3, z: 1 },
        Location { x: 1, y: 2, z: 1 },
        Location { x: 2, y: 1, z: 1 },
        Location { x: 3, y: 0, z: 1 },
    ],
    [
        Location { x: 0, y: 3, z: 2 },
        Location { x: 1, y: 2, z: 2 },
        Location { x: 2, y: 1, z: 2 },
        Location { x: 3, y: 0, z: 2 },
    ],
    [
        Location { x: 0, y: 3, z: 3 },
        Location { x: 1, y: 2, z: 3 },
        Location { x: 2, y: 1, z: 3 },
        Location { x: 3, y: 0, z: 3 },
    ],
    [
        Location { x: 0, y: 3, z: 0 },
        Location { x: 1, y: 2, z: 1 },
        Location { x: 2, y: 1, z: 2 },
        Location { x: 3, y: 0, z: 3 },
    ],
    [
        Location { x: 0, y: 3, z: 3 },
        Location { x: 1, y: 2, z: 2 },
        Location { x: 2, y: 1, z: 1 },
        Location { x: 3, y: 0, z: 0 },
    ],
];
